# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PrimeTime Brewers
next_meeting: >
  Wednesday, February 21, 2018 7PM
  Bier Distillery
  5295 West River Dr NE #100
  Comstock Park
tagline: West Michigan's Premiere Homebrewing Club
baseurl: "/primetimebrewers" # the subpath of your site, e.g. /blog
url: "https://dotps1.github.io" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Thomas'
  last_name: 'Malkewitz'
  email: primetimebrewersmi@gmail.com
  logo: '/images/PTB.png'
  facebook: https://www.facebook.com/PrimeTimeBrewers/
  paypal: https://www.paypal.me/PrimeTimeBrewers/

about: >
  The Primetime Brewers are a West Michigan homebrew club, based in Grand Rapids.   
  We have meetings the 3rd Wednesday of every month at 7pm.  
  Well, we actually meet at 6, if you have a beer for judging:
  6:00 to participate in judging the style of the month, 7:00 is the start of the meeting. We encourage everyone, members or not, to come to meetings and check us out.  
  Bring your homebrew to share and get feedback from experience brewers.
  We also gather informally the first Thursday of the month for what we call "Thursty Thirsday" at one of the local beer bars or breweries, where we enjoy Happy Hour.
  Our members are first time brewers all the way up to national award winners and professional brewers. 
  We are an American Homebrewers Association sanctioned club.  
  We participate in AHA functions, such as Learn to Homebrew Day, Big Brew and Mead Day.  
  We have two major club activities during the year, Pig Roast in September, and our Christmas Party/Auction in December.  
  Our dues are $20.
  Your membership card gets you 10% off homebrew supplies from our local vendors.  
  Check this website for times and dates of our meetings and functions.
  Please contact us if you have any questions at primetimebrewersmi@gmail.com or hit up one of our officers.

google:
  calendar_id: 2dg9b3ten4cc6ef752hpfvbbp8@group.calendar.google.com
  api_key: AIzaSyDMSiavMkwBvw9Pl-WP_NMYwQ4Rgb7v_rI

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html
